apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-docker-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-docker-image
  template:
    metadata:
      labels:
        app: my-docker-image
    spec:
      containers:
        - name: my-docker-image
          image: sadeghhs/my-docker-image:v1
          ports:
            - containerPort: 5000
