apiVersion: v1
kind: Service
metadata:
  name: my-docker-image-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.123.124.1
  selector:
    app: my-docker-image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000